"use client";

/**
 * Student Caste Wise Gender Count Report —
 * Angular `reports/admin-student-reports/student-Caste-wise-gender-count-report` parity.
 * Get List: `getAllRecords/s_get_student_reports?in_flag=caste_wise_gender_count_report&…`
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import type { ColDef, ColGroupDef } from "ag-grid-community";
import { FileSpreadsheet } from "lucide-react";
import { Select } from "@/common/components/select";
import {
  buildHtmlTable,
  escapeHtml,
  exportHtmlTableAsExcel,
} from "@/common/export-html-table";
import { FilteredListPage } from "@/components/layout";
import { Button } from "@/components/ui/button";
import { getErrorMessage } from "@/lib/errors";
import { resolveReportCatalogHref } from "@/lib/report-catalog";
import { toastError, toastInfo } from "@/lib/toast";
import { rowIndexGetter } from "@/lib/utils";
import {
  filterAcademicYears,
  filterColleges,
  filterCourseGroups,
  filterCourses,
  filterCourseYears,
  pickNum,
  pickText,
  type FilterRow,
} from "@/app/(pages)/(protected)/accounts-and-fees/fee-masters/_lib/fee-master-filters";
import { fetchStudentReports, getFeePaylinkCollegeFilters } from "@/services";

type AnyRow = Record<string, unknown>;

type GenderCell = { caste: string; gender: string; count: number };
type BranchRow = { Branch: string; studentCasteCount: GenderCell[] };

const ALL0 = { value: "0", label: "All" };

function gmOptions(rows: FilterRow[], gmId: number) {
  return rows
    .filter((r) => Number(r.pk_gm_id ?? r.generalMasterId ?? 0) === gmId)
    .map((r) => ({
      value: String(r.pk_gd_id ?? r.generalDetailId ?? ""),
      label: String(r.gd_name ?? r.generalDetailDisplayName ?? r.gd_code ?? ""),
    }))
    .filter((o) => o.value && o.value !== "0");
}

/** Angular caste/gender pivot shaping for `caste_wise_gender_count_report`. */
function buildCasteGenderMatrix(raw: AnyRow[]): {
  keys: { Caste: string }[];
  casteCount: BranchRow[];
} {
  // Keep caste order exactly as returned by API.
  // Ignore "Total Count" because React will calculate it.
  const casteNames: string[] = [];

  for (const row of raw) {
    const rawCaste = row.Caste;

    // Convert null/undefined to empty string.
    const caste =
      rawCaste === null || rawCaste === undefined
        ? ""
        : String(rawCaste).trim();

    // Total Count is generated by us, not treated as a caste.
    if (caste === "Total Count") {
      continue;
    }

    if (!casteNames.includes(caste)) {
      casteNames.push(caste);
    }
  }

  // Always add exactly ONE Total Count column.
  const keys = [
    ...casteNames.map((Caste) => ({ Caste })),
    { Caste: "Total Count" },
  ];

  const casteCount: BranchRow[] = [];

  for (const row of raw) {
    const branch = String(row.Branch ?? "");

    const caste =
      row.Caste === null || row.Caste === undefined
        ? ""
        : String(row.Caste).trim();

    // Do not add API Total Count rows.
    if (caste === "Total Count") {
      continue;
    }

    const gender = String(row.Gender ?? "").trim();

    const count = Number(row.Student_Count ?? 0);

    let branchEntry = casteCount.find((item) => item.Branch === branch);

    if (!branchEntry) {
      branchEntry = {
        Branch: branch,
        studentCasteCount: [],
      };

      casteCount.push(branchEntry);
    }

    const existingCell = branchEntry.studentCasteCount.find(
      (cell) => cell.caste === caste && cell.gender === gender,
    );

    if (existingCell) {
      existingCell.count = count;
    } else {
      branchEntry.studentCasteCount.push({
        caste,
        gender,
        count,
      });
    }
  }

  // Make sure every branch has Male/Female
  // for every caste column.
  for (const branch of casteCount) {
    for (const caste of casteNames) {
      for (const gender of ["Male", "Female"]) {
        const exists = branch.studentCasteCount.some(
          (cell) => cell.caste === caste && cell.gender === gender,
        );

        if (!exists) {
          branch.studentCasteCount.push({
            caste,
            gender,
            count: 0,
          });
        }
      }
    }

    // Calculate total from caste columns.
    let maleTotal = 0;
    let femaleTotal = 0;

    for (const cell of branch.studentCasteCount) {
      if (cell.gender === "Male") {
        maleTotal += Number(cell.count) || 0;
      }

      if (cell.gender === "Female") {
        femaleTotal += Number(cell.count) || 0;
      }
    }

    // Add exactly one Male total.
    branch.studentCasteCount.push({
      caste: "Total Count",
      gender: "Male",
      count: maleTotal,
    });

    // Add exactly one Female total.
    branch.studentCasteCount.push({
      caste: "Total Count",
      gender: "Female",
      count: femaleTotal,
    });
  }

  return {
    keys,
    casteCount,
  };
}

function flattenCasteRows(
  keys: { Caste: string }[],
  casteCount: BranchRow[],
): AnyRow[] {
  return casteCount.map((branch) => {
    const row: AnyRow = { Branch: branch.Branch };
    keys.forEach((k, ci) => {
      const male = branch.studentCasteCount.find(
        (c) => c.caste === k.Caste && c.gender === "Male",
      );
      const female = branch.studentCasteCount.find(
        (c) => c.caste === k.Caste && c.gender === "Female",
      );
      row[`c${ci}_m`] = male?.count ?? 0;
      row[`c${ci}_f`] = female?.count ?? 0;
    });
    return row;
  });
}

const REPORT_TITLE = "Student Caste Wise Gender Count Report";

export default function StudentCasteWiseGenderCountPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [filtersData, setFiltersData] = useState<FilterRow[]>([]);
  const [academicData, setAcademicData] = useState<FilterRow[]>([]);
  const [gmRows, setGmRows] = useState<FilterRow[]>([]);
  const [loadingFilters, setLoadingFilters] = useState(true);

  const [collegeId, setCollegeId] = useState<string | null>(null);
  const [academicYearId, setAcademicYearId] = useState<string>("0");
  const [courseId, setCourseId] = useState<string>("0");
  const [courseGroupId, setCourseGroupId] = useState<string>("0");
  const [courseYearId, setCourseYearId] = useState<string>("0");
  const [quotaId, setQuotaId] = useState<string>("0");
  const [studentStatusId, setStudentStatusId] = useState<string>("0");

  const [casteKeys, setCasteKeys] = useState<{ Caste: string }[]>([]);
  const [rows, setRows] = useState<AnyRow[]>([]);
  const [dataDetails, setDataDetails] = useState("");
  const [loadingList, setLoadingList] = useState(false);
  const [showTable, setShowTable] = useState(false);

  const clearResults = useCallback(() => {
    setCasteKeys([]);
    setRows([]);
    setShowTable(false);
    setDataDetails("");
  }, []);

  useEffect(() => {
    const orgId = Number(
      globalThis.localStorage?.getItem("organizationId") ?? 0,
    );
    const empId = Number(globalThis.localStorage?.getItem("employeeId") ?? 0);
    if (!orgId || !empId) {
      setLoadingFilters(false);
      return;
    }
    let cancelled = false;
    setLoadingFilters(true);
    void getFeePaylinkCollegeFilters(orgId, empId)
      .then((data) => {
        if (cancelled) return;
        setFiltersData((data.filtersData ?? []) as FilterRow[]);
        setAcademicData((data.academicData ?? []) as FilterRow[]);
        setGmRows((data.generalDetails ?? []) as FilterRow[]);
      })
      .catch((err) => {
        if (!cancelled) toastError(getErrorMessage(err));
      })
      .finally(() => {
        if (!cancelled) setLoadingFilters(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const collegeOptions = useMemo(
    () =>
      filterColleges(filtersData).map((r) => ({
        value: String(pickNum(r, ["fk_college_id", "collegeId"])),
        label: pickText(r, ["college_code", "collegeCode"]),
      })),
    [filtersData],
  );

  const ayOptions = useMemo(() => {
    const cid = Number(collegeId ?? 0);
    return [
      ALL0,
      ...filterAcademicYears(academicData, cid || null, filtersData).map(
        (r) => ({
          value: String(pickNum(r, ["fk_academic_year_id", "academicYearId"])),
          label: pickText(r, ["academic_year", "academicYear"]) || "—",
        }),
      ),
    ];
  }, [academicData, collegeId, filtersData]);

  const courseOptions = useMemo(() => {
    const cid = Number(collegeId ?? 0);
    return [
      ALL0,
      ...filterCourses(filtersData, cid || null).map((r) => ({
        value: String(pickNum(r, ["fk_course_id", "courseId"])),
        label: pickText(r, ["course_code", "courseCode", "course_name"]),
      })),
    ];
  }, [filtersData, collegeId]);

  const groupOptions = useMemo(() => {
    const cid = Number(collegeId ?? 0);
    const cr = Number(courseId || 0);
    return [
      ALL0,
      ...filterCourseGroups(filtersData, cid || null, cr || null).map((r) => ({
        value: String(pickNum(r, ["fk_course_group_id", "courseGroupId"])),
        label: pickText(r, ["group_code", "groupCode", "courseGroupCode"]),
      })),
    ];
  }, [filtersData, collegeId, courseId]);

  const yearOptions = useMemo(() => {
    const cid = Number(collegeId ?? 0);
    const cr = Number(courseId || 0);
    const g = Number(courseGroupId || 0);
    return [
      ALL0,
      ...filterCourseYears(filtersData, cid || null, cr || null, g || null)
        .sort(
          (a, b) =>
            pickNum(a, ["year_order", "sortOrder"]) -
            pickNum(b, ["year_order", "sortOrder"]),
        )
        .map((r) => ({
          value: String(pickNum(r, ["fk_course_year_id", "courseYearId"])),
          label: pickText(r, ["course_year_name", "courseYearName"]),
        })),
    ];
  }, [filtersData, collegeId, courseId, courseGroupId]);

  const quotaOptions = useMemo(() => [ALL0, ...gmOptions(gmRows, 8)], [gmRows]);
  const statusOptions = useMemo(
    () => [ALL0, ...gmOptions(gmRows, 51)],
    [gmRows],
  );

  useEffect(() => {
    if (collegeId || collegeOptions.length === 0) return;
    setCollegeId(collegeOptions[0].value);
  }, [collegeId, collegeOptions]);

  useEffect(() => {
    if (!collegeId) return;
    const rowsAy = filterAcademicYears(
      academicData,
      Number(collegeId),
      filtersData,
    );
    if (rowsAy.length === 0) {
      setAcademicYearId("0");
      setCourseId("0");
      setCourseGroupId("0");
      setCourseYearId("0");
      return;
    }
    const current =
      rowsAy.find((r) => Number(r.is_curr_ay ?? 0) === 1) ?? rowsAy[0];
    setAcademicYearId(
      String(pickNum(current, ["fk_academic_year_id", "academicYearId"])),
    );
  }, [collegeId]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!collegeId || !academicYearId) return;
    const courses = courseOptions.filter((o) => o.value !== "0");
    if (courses.length === 0) {
      setCourseId("0");
      setCourseGroupId("0");
      setCourseYearId("0");
      return;
    }
    setCourseId(courses[0].value);
  }, [collegeId, academicYearId]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!courseId || courseId === "0") {
      setCourseGroupId("0");
      setCourseYearId("0");
      return;
    }
    const groups = groupOptions.filter((o) => o.value !== "0");
    setCourseGroupId(groups[0]?.value ?? "0");
  }, [courseId]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!courseGroupId || courseGroupId === "0") {
      setCourseYearId("0");
      return;
    }
    const years = yearOptions.filter((o) => o.value !== "0");
    setCourseYearId(years[0]?.value ?? "0");
  }, [courseGroupId]); // eslint-disable-line react-hooks/exhaustive-deps

  const onCollegeChange = (v: string | null) => {
    setCollegeId(v);
    setAcademicYearId("0");
    setCourseId("0");
    setCourseGroupId("0");
    setCourseYearId("0");
    setQuotaId("0");
    setStudentStatusId("0");
    clearResults();
  };

  const buildDataDetails = () => {
    const parts: string[] = [];
    const clg = collegeOptions.find((o) => o.value === collegeId);
    if (clg?.label) parts.push(clg.label);
    const ay = ayOptions.find(
      (o) => o.value === academicYearId && o.value !== "0",
    );
    if (ay?.label) parts.push(ay.label);
    const cr = courseOptions.find(
      (o) => o.value === courseId && o.value !== "0",
    );
    if (cr?.label) parts.push(cr.label);
    const g = groupOptions.find(
      (o) => o.value === courseGroupId && o.value !== "0",
    );
    if (g?.label) parts.push(g.label);
    const y = yearOptions.find(
      (o) => o.value === courseYearId && o.value !== "0",
    );
    if (y?.label) parts.push(y.label);
    const q = quotaOptions.find((o) => o.value === quotaId && o.value !== "0");
    if (q?.label) parts.push(q.label);
    const st = statusOptions.find(
      (o) => o.value === studentStatusId && o.value !== "0",
    );
    if (st?.label) parts.push(st.label);
    return parts.join(" / ");
  };

  const handleGetList = async () => {
    const cid = Number(collegeId ?? 0);

    if (!cid) {
      toastInfo("College is required");
      return;
    }

    setLoadingList(true);
    clearResults();

    const details = buildDataDetails();
    setDataDetails(details);

    try {
      const raw = await fetchStudentReports({
        flag: "caste_wise_gender_count_report",
        fromDate: "1990-01-01",
        toDate: "1990-01-01",
        collegeId: cid,
        courseId: Number(courseId || 0),
        academicYearId: Number(academicYearId || 0),
        courseGroupId: Number(courseGroupId || 0),
        courseYearId: Number(courseYearId || 0),
        quotaId: Number(quotaId || 0),
        regulationId: 0,
        isCurrentYear: -1,
        isLateral: -1,
        appStatus: 0,
        studentStatusIds: Number(studentStatusId || 0),
      });

      if (raw.length === 0) {
        toastInfo("No caste wise gender count records found.");
        return;
      }

      const shaped = buildCasteGenderMatrix(raw);

      setCasteKeys(shaped.keys);
      setRows(flattenCasteRows(shaped.keys, shaped.casteCount));
      setShowTable(true);
    } catch (err) {
      toastError(getErrorMessage(err));
    } finally {
      setLoadingList(false);
    }
  };

  const columnDefs = useMemo<(ColDef<AnyRow> | ColGroupDef<AnyRow>)[]>(() => {
    const spannedLeaf: Partial<ColDef<AnyRow>> = {
      autoHeaderHeight: false,
      wrapHeaderText: false,
      suppressSpanHeaderHeight: false,
      suppressHeaderMenuButton: true,
    };
    const defs: (ColDef<AnyRow> | ColGroupDef<AnyRow>)[] = [
      {
        headerName: "S.No",
        valueGetter: rowIndexGetter,
        width: 80,
        flex: 0,
        ...spannedLeaf,
        headerClass: "quota-span-header quota-span-header--center",
        cellClass: "text-center",
      },
      {
        field: "Branch",
        headerName: "Branch",
        minWidth: 160,
        ...spannedLeaf,
        headerClass: "quota-span-header",
      },
    ];
    casteKeys.forEach((k, ci) => {
      defs.push({
        headerName: k.Caste,
        headerClass: "app-table-header-group",
        marryChildren: true,
        children: [
          {
            field: `c${ci}_m`,
            headerName: "M",
            width: 80,
            minWidth: 70,
            flex: 0,
            cellClass: "text-center",
            suppressHeaderMenuButton: true,
          },
          {
            field: `c${ci}_f`,
            headerName: "F",
            width: 80,
            minWidth: 70,
            flex: 0,
            cellClass: "text-center",
            suppressHeaderMenuButton: true,
          },
        ],
      });
    });
    return defs;
  }, [casteKeys]);

  const excelColumns = useMemo(() => {
    const cols: { key: string; header: string }[] = [
      { key: "siNo", header: "S.No" },
      { key: "Branch", header: "Branch" },
    ];
    casteKeys.forEach((k, ci) => {
      cols.push({ key: `c${ci}_m`, header: `${k.Caste} M` });
      cols.push({ key: `c${ci}_f`, header: `${k.Caste} F` });
    });
    return cols;
  }, [casteKeys]);

  const exportFlatRows = useMemo(
    () =>
      rows.map((row, i) => {
        const flat: Record<string, unknown> = {
          siNo: i + 1,
          Branch: String(row.Branch ?? ""),
        };
        casteKeys.forEach((_, ci) => {
          flat[`c${ci}_m`] = row[`c${ci}_m`] ?? 0;
          flat[`c${ci}_f`] = row[`c${ci}_f`] ?? 0;
        });
        return flat;
      }),
    [casteKeys, rows],
  );

  const handleExcelExport = useCallback(() => {
    if (exportFlatRows.length === 0) {
      toastError("No records to export.");
      return;
    }
    const headerHtml = `<div style="text-align:center;margin-bottom:12px;">
      <div style="font-size:14px;font-weight:bold;">${escapeHtml(REPORT_TITLE)}${dataDetails ? ` - ${escapeHtml(dataDetails)}` : ""}</div>
    </div>`;
    const tableHtml = buildHtmlTable(excelColumns, exportFlatRows);
    exportHtmlTableAsExcel(`${REPORT_TITLE}.xls`, tableHtml, headerHtml);
  }, [dataDetails, excelColumns, exportFlatRows]);

  const goBack = () => {
    router.push(resolveReportCatalogHref(searchParams.get("path")));
  };

  const pageTitle = showTable
    ? dataDetails
      ? `${REPORT_TITLE} — ${dataDetails}`
      : REPORT_TITLE
    : REPORT_TITLE;

  return (
    <>
      <style>{`
        .app-data-table .ag-theme-quartz .ag-header-cell.quota-span-header {
          align-items: center;
        }
        .app-data-table .ag-theme-quartz .ag-header-cell.quota-span-header .ag-header-cell-comp-wrapper {
          height: 100%;
          display: flex;
          align-items: center;
        }
        .app-data-table .ag-theme-quartz .ag-header-cell.quota-span-header .ag-header-cell-label {
          height: 100%;
          display: flex;
          align-items: center;
        }
        .app-data-table .ag-theme-quartz .ag-header-cell.quota-span-header--center .ag-header-cell-label {
          justify-content: center;
        }
      `}</style>
      <FilteredListPage
        title={pageTitle}
        filters={
          <div className="space-y-3">
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
              <Select
                label="College"
                required
                value={collegeId}
                onChange={onCollegeChange}
                options={collegeOptions}
                placeholder="College"
                isLoading={loadingFilters}
              />
              <Select
                label="Academic Year"
                value={academicYearId}
                onChange={(v) => {
                  setAcademicYearId(v ?? "0");
                  clearResults();
                }}
                options={ayOptions}
                placeholder="Academic Year"
              />
              <Select
                label="Course"
                value={courseId}
                onChange={(v) => {
                  setCourseId(v ?? "0");
                  clearResults();
                }}
                options={courseOptions}
                placeholder="Course"
                disabled={!collegeId}
              />
              <Select
                label="CourseGroup"
                value={courseGroupId}
                onChange={(v) => {
                  setCourseGroupId(v ?? "0");
                  clearResults();
                }}
                options={groupOptions}
                placeholder="CourseGroup"
              />
              <Select
                label="Course Year"
                value={courseYearId}
                onChange={(v) => {
                  setCourseYearId(v ?? "0");
                  clearResults();
                }}
                options={yearOptions}
                placeholder="Course Year"
              />
            </div>
            <div className="flex flex-wrap items-end gap-3">
              <div className="w-full min-w-[10rem] sm:w-[12rem]">
                <Select
                  label="Quota"
                  value={quotaId}
                  onChange={(v) => {
                    setQuotaId(v ?? "0");
                    clearResults();
                  }}
                  options={quotaOptions}
                  placeholder="Quota"
                />
              </div>
              <div className="w-full min-w-[10rem] sm:w-[14rem]">
                <Select
                  label="Student Status"
                  required
                  value={studentStatusId}
                  onChange={(v) => {
                    setStudentStatusId(v ?? "0");
                    clearResults();
                  }}
                  options={statusOptions}
                  placeholder="Student Status"
                />
              </div>
              <div className="flex shrink-0 items-center gap-2 pb-0.5">
                <Button
                  type="button"
                  className="h-9 w-fit px-4"
                  disabled={loadingList}
                  onClick={() => void handleGetList()}
                >
                  {loadingList ? "Loading…" : "Get Student List"}
                </Button>
                <Button
                  type="button"
                  variant="secondary"
                  className="h-9 w-fit px-4"
                  onClick={goBack}
                >
                  Back
                </Button>
              </div>
            </div>
          </div>
        }
        rowData={showTable ? rows : []}
        columnDefs={columnDefs}
        pagination
        loading={loadingList || loadingFilters}
        resultsVisible={showTable}
        hideEmptyGrid
        columnFilters={false}
        fitColumnsToWidth={false}
        toolbar={{
          search: true,
          searchPlaceholder: "Search",
          exportExcel: false,
          exportPdf: false,
          columnFilters: false,
        }}
        toolbarTrailing={
          showTable ? (
            <Button
              type="button"
              size="sm"
              className="h-9 px-3 text-[12px]"
              onClick={handleExcelExport}
            >
              <FileSpreadsheet className="mr-1.5 h-3.5 w-3.5" />
              Export Excel
            </Button>
          ) : null
        }
      />
    </>
  );
}
