import type { ErpModuleMirrorConfig, ModuleRouteConfig } from './types'

function r(
  slug: string,
  title: string,
  description: string,
  kind: ModuleRouteConfig['kind'] = 'placeholder',
): ModuleRouteConfig {
  return { slug, title, description, kind, angularPath: slug }
}

export const TRANSPORT_MODULE: ErpModuleMirrorConfig = {
  id: 'transport',
  basePath: '/transport',
  angularSegment: 'transport/',
  defaultSlug: 'transport-dashboard',
  moduleLabel: 'Transport',
  dashboardTitle: 'Transport Dashboard',
  dashboardDescription:
    'Manage vehicles, routes, drivers, transport allocation, and student transport details.',
  labelAliases: {
    // Transport sidebar labels (incl. Angular typos from live menu)
    addroute: 'route',
    mapvechicleroute: 'vehicle-map',
    mapvehicleroute: 'vehicle-map',
    mapvehicledriver: 'vehicle-drivers',
    mapvehicledrivers: 'vehicle-drivers',
    transportdistancefee: 'distance-fee',
    transportdetails: 'transport-details',
    transportallocatedlist: 'transport-allocated-list',
    transportallocation: 'transport-allocation',
    studenttransportdetails: 'student-transport-details',
    vehicledrivers: 'vehicle-drivers',
    vehiclemap: 'vehicle-map',
    distancefee: 'distance-fee',
    routestops: 'route-stops',
  },
  slugAliases: {
    transportdetails: 'transport-details',
    transportallocatedlist: 'transport-allocated-list',
    transportallocation: 'transport-allocation',
    studenttransportdetails: 'student-transport-details',
    vehicledrivers: 'vehicle-drivers',
    vehiclemap: 'vehicle-map',
    mapvehicleroute: 'vehicle-map',
    distancefee: 'distance-fee',
    routestops: 'route-stops',
  },
  routes: [
    r('transport-dashboard', 'Transport Dashboard', 'Overview of transport operations.', 'dashboard'),
    r('transport-details', 'Transport Details', 'Transport service configuration.', 'master'),
    r('vehicle', 'Vehicle', 'Register and maintain vehicles.', 'master'),
    r('driver', 'Driver', 'Driver master data.', 'master'),
    r('helper', 'Helper', 'Transport helper staff.', 'master'),
    r('route', 'Add Route', 'Bus routes and schedules.', 'master'),
    r('route-stops', 'Route Stops', 'Stops along each route.', 'master'),
    r('vehicle-drivers', 'Map Vehicle Driver', 'Assign drivers to vehicles.', 'transaction'),
    r('vehicle-map', 'Map Vehicle Route', 'Assign vehicles to routes (vehicle route mapping).', 'master'),
    r('distance-fee', 'Distance Fee', 'Fee by distance slabs.', 'master'),
    r('transport-allocation', 'Transport Allocation', 'Allocate students to routes.', 'transaction'),
    r('transport-allocated-list', 'Allocated List', 'View and edit allocations.', 'report'),
    r('student-transport-details', 'Student Transport Details', 'Student-wise transport info.', 'report'),
  ],
}

export const TC_NO_DUE_MODULE: ErpModuleMirrorConfig = {
  id: 'tc-no-due-approval',
  basePath: '/tc-no-due-approval',
  angularSegment: 'certificates/',
  defaultSlug: 'transfer-certificate',
  moduleLabel: 'TC and NO Due Approval',
  dashboardTitle: 'TC & No Due Approval',
  dashboardDescription:
    'Transfer certificate workflow, no-due clearance requests, and certificate request approvals.',
  labelAliases: {
    transfercertificate: 'transfer-certificate',
    nodueapprovalrequest: 'send-no-due-approval-request',
    nodueapproval: 'send-no-due-approval-request',
    sendnodueapprovalrequest: 'send-no-due-approval-request',
    certificaterequests: 'certificate-requests',
    certificatesissued: 'certificates-issued-list',
    certificatesissuedlist: 'certificates-issued-list',
    certificaterequestreport: 'certificate-request-report',
    printtc: 'certificate-requests/printTc',
  },
  slugAliases: {
    printtc: 'certificate-requests/printTc',
    nodue: 'send-no-due-approval-request',
    nodueapproval: 'send-no-due-approval-request',
    transfercertificate: 'transfer-certificate',
    certificaterequests: 'certificate-requests',
    certificatesissuedlist: 'certificates-issued-list',
  },
  routes: [
    r('transfer-certificate', 'Transfer Certificate', 'TC application and processing.', 'transaction'),
    r(
      'send-no-due-approval-request',
      'No Due Approval Request',
      'Send departments for no-due clearance.',
      'transaction',
    ),
    r('certificate-requests', 'Certificate Requests', 'Pending certificate approvals.', 'transaction'),
    r(
      'certificate-requests/printTc',
      'Print TC',
      'Print transfer certificate.',
      'transaction',
    ),
    r('certificates-issued-list', 'Certificates Issued', 'Issued certificates list.', 'report'),
    r('certificate-request-report', 'Certificate Request Report', 'Request status report.', 'report'),
  ],
}

export const HOSTEL_MODULE: ErpModuleMirrorConfig = {
  id: 'hostel',
  basePath: '/hostel',
  angularSegment: 'hostel/',
  defaultSlug: 'hostel-dashboard',
  moduleLabel: 'Hostel',
  dashboardTitle: 'Hostel Dashboard',
  dashboardDescription:
    'Hostel types, rooms, allocation, visitors, payments, and occupancy reports.',
  labelAliases: {
    hosteltypes: 'hostel-types',
    hosteldetails: 'hostel-details',
    roomcharges: 'room-charges',
    roomslist: 'rooms-list',
    roomallocation: 'rooms-list',
    hostelroomallocation: 'rooms-list',
    viewroomdetails: 'view-room-details',
    hosteldiscounts: 'hostel-discounts',
    hostelregister: 'hostel-register',
    hostelvisitor: 'hostel-visitor',
    hostelpayment: 'hostel-payment',
    monthlyvisitorsummaryreport: 'monthly-visitor-summary-report',
    monthlyvisitorsummary: 'monthly-visitor-summary-report',
  },
  slugAliases: {
    hosteltypes: 'hostel-types',
    hosteldetails: 'hostel-details',
    roomcharges: 'room-charges',
    roomslist: 'rooms-list',
    roomallocation: 'rooms-list',
    hostelroomallocation: 'rooms-list',
    hosteldiscounts: 'hostel-discounts',
    hostelregister: 'hostel-register',
    hostelvisitor: 'hostel-visitor',
    hostelpayment: 'hostel-payment',
  },
  routes: [
    r('hostel-dashboard', 'Hostel Dashboard', 'Hostel overview.', 'dashboard'),
    r('hostel-types', 'Hostel Types', 'Categories of hostel accommodation.', 'master'),
    r('hostel-details', 'Hostel Details', 'Hostel buildings and blocks.', 'master'),
    r('room-charges', 'Room Charges', 'Room fee structures.', 'master'),
    r('rooms', 'Rooms', 'Room inventory.', 'master'),
    r('rooms-list', 'Hostel Room Allocation', 'Select hostel and allocate students to rooms.', 'transaction'),
    r('room-allocation', 'Allocate to Room', 'Assign student or employee to a room bed.', 'transaction'),
    r('view-room-details', 'View Room Details', 'Room occupancy details.', 'report'),
    r('hostel-discounts', 'Hostel Discounts', 'Discount rules for hostel fees.', 'master'),
    r('hostel-register', 'Hostel Register', 'Hostel register entries.', 'transaction'),
    r('hostel-visitor', 'Hostel Visitor', 'Visitor log.', 'transaction'),
    r('hostel-payment', 'Hostel Payment', 'Hostel fee collection.', 'transaction'),
    r(
      'monthly-visitor-summary-report',
      'Monthly Visitor Summary',
      'Visitor summary report.',
      'report',
    ),
  ],
}

export const CERTIFICATES_MODULE: ErpModuleMirrorConfig = {
  id: 'certificates',
  basePath: '/certificates',
  angularSegment: 'certificates/',
  defaultSlug: 'certificates-dashboard',
  moduleLabel: 'Certificates',
  dashboardTitle: 'Certificates Dashboard',
  dashboardDescription: 'Issue and track bonafide, TC, custodian, and other certificates.',
  labelAliases: {
    certificates: 'certificates-dashboard',
    certificatedashboard: 'certificates-dashboard',
    certificatesdashboard: 'certificates-dashboard',
    bonafidecertificate: 'bonafied-certificate',
    bonafiedcertificate: 'bonafied-certificate',
    bonafideconductcertificate: 'bonafide-conduct-certificate',
    transfercertificate: 'transfer-certificate',
    custodiancertificate: 'custodian-certificate',
    coursecompletioncertificate: 'course-completion-certificate',
    mediumofinstructioncertificate: 'medium-of-instruction-certificate',
    mediumofinstruction: 'medium-of-instruction-certificate',
    noobjectioncertificate: 'no-objection-certificate',
    certificaterequests: 'certificate-requests',
    certificatesissuedlist: 'certificates-issued-list',
    certificatesissued: 'certificates-issued-list',
    nodueapprovalrequest: 'send-no-due-approval-request',
    nodueapproval: 'send-no-due-approval-request',
    sendnodueapprovalrequest: 'send-no-due-approval-request',
    certificaterequestreport: 'certificate-request-report',
    printcertificatereceipt: 'certificate-requests/print-certificate-receipt',
    printtc: 'certificate-requests/printTc',
  },
  slugAliases: {
    bonafide: 'bonafied-certificate',
    bonafied: 'bonafied-certificate',
    bonafidecertificate: 'bonafied-certificate',
    bonafiedcertificate: 'bonafied-certificate',
    bonafideconductcertificate: 'bonafide-conduct-certificate',
    transfercertificate: 'transfer-certificate',
    custodiancertificate: 'custodian-certificate',
    coursecompletioncertificate: 'course-completion-certificate',
    mediumofinstruction: 'medium-of-instruction-certificate',
    mediumofinstructioncertificate: 'medium-of-instruction-certificate',
    noobjectioncertificate: 'no-objection-certificate',
    certificaterequests: 'certificate-requests',
    certificatesissuedlist: 'certificates-issued-list',
    certificatesissued: 'certificates-issued-list',
    nodueapproval: 'send-no-due-approval-request',
    nodueapprovalrequest: 'send-no-due-approval-request',
    sendnodueapprovalrequest: 'send-no-due-approval-request',
    certificaterequestreport: 'certificate-request-report',
    printtc: 'certificate-requests/printTc',
    printcertificatereceipt: 'certificate-requests/print-certificate-receipt',
  },
  routes: [
    r('certificates-dashboard', 'Certificates Dashboard', 'Certificates overview.', 'dashboard'),
    r('bonafied-certificate', 'Bonafide Certificate', 'Bonafide certificate requests.', 'transaction'),
    r(
      'bonafide-conduct-certificate',
      'Bonafide Conduct Certificate',
      'Conduct certificate.',
      'transaction',
    ),
    r('transfer-certificate', 'Transfer Certificate', 'Transfer certificate.', 'transaction'),
    r('custodian-certificate', 'Custodian Certificate', 'Custodian certificate.', 'transaction'),
    r(
      'course-completion-certificate',
      'Course Completion Certificate',
      'Course completion certificate.',
      'transaction',
    ),
    r(
      'medium-of-instruction-certificate',
      'Medium of Instruction',
      'Medium of instruction certificate.',
      'transaction',
    ),
    r('no-objection-certificate', 'No Objection Certificate', 'NOC certificate.', 'transaction'),
    r('certificate-requests', 'Certificate Requests', 'All certificate requests.', 'transaction'),
    r('certificates-issued-list', 'Certificates Issued List', 'Issued certificates.', 'report'),
    r(
      'send-no-due-approval-request',
      'No Due Approval',
      'No-due approval workflow.',
      'transaction',
    ),
    r('certificate-request-report', 'Certificate Request Report', 'Request analytics.', 'report'),
    r(
      'certificate-requests/print-certificate-receipt',
      'Print Certificate Receipt',
      'Print fee receipt.',
      'transaction',
    ),
    r('certificate-requests/printTc', 'Print TC', 'Print transfer certificate.', 'transaction'),
  ],
}

export const CAMPUS_MAINTENANCE_MODULE: ErpModuleMirrorConfig = {
  id: 'campus-maintenance',
  basePath: '/campus-maintenance',
  angularSegment: 'campus-maintenance/',
  defaultSlug: 'campus-maintendance-dashboard',
  moduleLabel: 'Campus Maintenance',
  dashboardTitle: 'Campus Maintenance Dashboard',
  dashboardDescription: 'Log complaints, track status, and maintain campus facilities.',
  slugAliases: {
    dashboard: 'campus-maintendance-dashboard',
    campusmaintenancedashboard: 'campus-maintendance-dashboard',
  },
  routes: [
    r(
      'campus-maintendance-dashboard',
      'Maintenance Dashboard',
      'Complaints overview.',
      'dashboard',
    ),
    r('complaints-list', 'Complaints List', 'All maintenance complaints.', 'report'),
    r('new-complaints', 'New Complaints', 'Raise a new complaint.', 'transaction'),
    r('add-complaints', 'Add Complaints', 'Add complaint details.', 'transaction'),
    r('complaint-status', 'Complaint Status', 'Update complaint status.', 'transaction'),
  ],
}

export const TRAININGS_MODULE: ErpModuleMirrorConfig = {
  id: 'trainings',
  basePath: '/trainings',
  angularSegment: 'trainings/',
  defaultSlug: 'training',
  moduleLabel: 'Trainings',
  dashboardTitle: 'Trainings',
  dashboardDescription:
    'Placement trainings, sessions, registration, attendance, and registered students.',
  slugAliases: {
    trainings: 'training',
    placementtrainings: 'training',
  },
  routes: [
    r('training', 'Trainings', 'Training programmes list.', 'dashboard'),
    r('training-details', 'Training Details', 'Training programme details.', 'master'),
    r('training-detail', 'Add Training Details', 'Create or edit training.', 'transaction'),
    r('training-sessions', 'Training Sessions', 'Schedule sessions.', 'transaction'),
    r(
      'student-training-registration',
      'Student Registration',
      'Register students for training.',
      'transaction',
    ),
    r('training-registered-list', 'Registered List', 'Students registered.', 'report'),
    r('attendance', 'Mark Attendance', 'Session attendance marking.', 'transaction'),
    r('view-training-attendance', 'View Attendance', 'Attendance reports.', 'report'),
    r('training-attendance', 'Training Classes', 'Classes list for attendance.', 'report'),
  ],
}

export const PLACEMENTS_MODULE: ErpModuleMirrorConfig = {
  id: 'placements-achievements',
  basePath: '/placements-achievements',
  angularSegment: 'placements-achievements/',
  defaultSlug: 'placements',
  moduleLabel: 'Placements & Achievements',
  dashboardTitle: 'Placements & Achievements',
  dashboardDescription: 'Record student placements and co-curricular achievements.',
  // Map Angular sidebar labels (normalised, lowercase, no spaces/symbols) → Next.js slug.
  // Needed when the DB href is missing or flat (e.g. `placements-achievements/companies`).
  labelAliases: {
    // ── Placements sub-module ────────────────────────────────────────────────
    placements:                   'placements/placements',
    placementlist:                'placements/placements',
    placementrecords:             'placements/placements',
    companies:                    'placements/companies',
    company:                      'placements/companies',
    companymaster:                'placements/companies',
    companycontacts:              'placements/company-contacts',
    companycontact:               'placements/company-contacts',
    contactpersons:               'placements/company-contacts',
    companymeetings:              'placements/company-meetings',
    companymeeting:               'placements/company-meetings',
    meetings:                     'placements/company-meetings',
    placementcompanies:           'placements/placement-companies',
    placementrequirements:        'placements/placement-companies',
    companyplacementrequirements: 'placements/placement-companies',
    companyplacementrequirement:  'placements/placement-companies',
    companyplacementsrequirements:'placements/placement-companies',
    requirements:                 'placements/placement-companies',
    placementbroadcast:           'placements/placement-broadcast',
    broadcast:                    'placements/placement-broadcast',
    broadcastmessages:            'placements/placement-broadcast',
    broadcastmessage:             'placements/placement-broadcast',
    placementregisteredlist:      'placements/placement-registered-list',
    placementstudentslist:        'placements/placement-registered-list',
    placementstudentlist:         'placements/placement-registered-list',
    placementregisteredstudentslist: 'placements/placement-registered-list',
    registeredstudents:           'placements/placement-registered-list',
    registeredlist:               'placements/placement-registered-list',
    placedstudents:               'placements/placed-students-list',
    placedstudentslist:           'placements/placed-students-list',
    placedlist:                   'placements/placed-students-list',
    // ── Achievements sub-module ──────────────────────────────────────────────
    achievements:                 'achievements/achievements',
    achievement:                  'achievements/achievements',
    achievementlist:              'achievements/achievements',
    achievementcategories:        'achievements/achievement-categories',
    achievementcategory:          'achievements/achievement-categories',
    categories:                   'achievements/achievement-categories',
    achievementsubcategories:     'achievements/achievement-sub-categories',
    achievementsubcategory:       'achievements/achievement-sub-categories',
    subcategories:                'achievements/achievement-sub-categories',
  },
  // Map flat Angular slugs (last URL segment) → nested Next.js slug.
  // Used by mapModuleTail when the href is flat, e.g. `placements-achievements/companies`.
  slugAliases: {
    companies:                    'placements/companies',
    'company-contacts':           'placements/company-contacts',
    companycontacts:              'placements/company-contacts',
    'company-meetings':           'placements/company-meetings',
    companymeetings:              'placements/company-meetings',
    'placement-companies':        'placements/placement-companies',
    placementcompanies:           'placements/placement-companies',
    'company-placements-requirements': 'placements/placement-companies',
    companyplacementsrequirements:     'placements/placement-companies',
    'placements/company-placements-requirements': 'placements/placement-companies',
    'placement-broadcast':        'placements/placement-broadcast',
    placementbroadcast:           'placements/placement-broadcast',
    'placement-registered-list':  'placements/placement-registered-list',
    placementregisteredlist:      'placements/placement-registered-list',
    'placement-registered-studentslist': 'placements/placement-registered-list',
    placementregisteredstudentslist:     'placements/placement-registered-list',
    'placements/placement-registered-studentslist': 'placements/placement-registered-list',
    'placed-students-list':       'placements/placed-students-list',
    placedstudentslist:           'placements/placed-students-list',
    'achievement-categories':     'achievements/achievement-categories',
    achievementcategories:        'achievements/achievement-categories',
    'achievement-sub-categories': 'achievements/achievement-sub-categories',
    achievementsubcategories:     'achievements/achievement-sub-categories',
  },
  routes: [
    // Sub-module parents (landing pages handled by placements/page.tsx and achievements/page.tsx)
    r('placements', 'Placements', 'Placement drives and records.', 'transaction'),
    r('achievements', 'Achievements', 'Student and staff achievements.', 'transaction'),
    // ── Placements pages ────────────────────────────────────────────────────
    r('placements/placements',            'Placements',                'Placement drives and employers.', 'transaction'),
    r('placements/companies',             'Companies',                 'Employer company master.',         'master'),
    r('placements/company-contacts',      'Company Contacts',          'Company contact persons.',         'master'),
    r('placements/company-meetings',      'Company Meetings',          'Meetings with companies.',         'transaction'),
    r('placements/placement-companies',   'Company Placement Requirements', 'Company-wise placement requirements.', 'transaction'),
    r('placements/placement-broadcast',   'Broadcast Messages',        'Placement broadcast notices by year and post type.', 'transaction'),
    r('placements/placement-registered-list', 'Placement Students List', 'Registered students and interview rounds.', 'report'),
    r('placements/placed-students-list',  'Placed Students',           'Students who have been placed.',   'report'),
    // ── Achievements pages ───────────────────────────────────────────────────
    r('achievements/achievements',              'Achievements',              'Student and staff achievements.', 'transaction'),
    r('achievements/achievement-categories',    'Achievement Categories',    'Achievement category master.',     'master'),
    r('achievements/achievement-sub-categories','Achievement Sub-Categories','Achievement sub-category master.', 'master'),
  ],
}

export const COMMITTEES_MODULE: ErpModuleMirrorConfig = {
  id: 'committees',
  basePath: '/committees',
  angularSegment: 'committe/',
  defaultSlug: 'create-committee',
  moduleLabel: 'Committees',
  dashboardTitle: 'Committees',
  dashboardDescription:
    'Committee setup, members, meetings, remuneration, and approval workflows.',
  slugAliases: {
    committee: 'create-committee',
    committe: 'create-committee',
  },
  labelAliases: {
    createcommittee: 'create-committee',
    createcommitteeposition: 'create-committee-position',
    addcommitteemembers: 'add-committee-members',
    schedulecommitteemeeting: 'schedule-committee-meeting',
    finaliseprofiles: 'finalise-profiles',
    finalisedprofiles: 'finalised-profiles',
    remunerationsettings: 'remuneration-settings',
    remunerationapprovals: 'remuneration-approvals',
    remunerationpayment: 'remuneration-payment',
  },
  routes: [
    r('create-committee', 'Create Committee', 'Define university committees.', 'master'),
    r('create-committee-position', 'Create Committee Position', 'Committee position master.', 'master'),
    r('add-committee-members', 'Add Committee Members', 'Assign members to committees.', 'master'),
    r('schedule-committee-meeting', 'Schedule Committee Meeting', 'Schedule committee meetings.', 'transaction'),
    r(
      'schedule-committee-meeting/add-meeting',
      'Add Meeting',
      'Add meeting details.',
      'transaction',
    ),
    r('finalise-profiles', 'Finalise Profiles', 'Finalise evaluator profiles for committees.', 'transaction'),
    r('finalised-profiles', 'Finalised Profiles', 'View finalised profiles and release offers.', 'report'),
    r('remuneration-settings', 'Remuneration Settings', 'Remuneration rate rules.', 'master'),
    r('remuneration-approvals', 'Remuneration Approvals', 'Approve examination remuneration.', 'transaction'),
    r('remuneration-payment', 'Remuneration Payment', 'Process remuneration payments.', 'transaction'),
    r('committee-meeting', 'Committee Meeting', 'Meeting records.', 'report'),
  ],
}

export const INVENTORY_MODULE: ErpModuleMirrorConfig = {
  id: 'inventory-management',
  basePath: '/inventory-management',
  angularSegment: 'inventory/',
  defaultSlug: 'stores-master',
  moduleLabel: 'Inventory Management',
  dashboardTitle: 'Inventory Management',
  dashboardDescription:
    'Store, item, supplier masters and purchase, stock receipt, indent, and issue workflows.',
  slugAliases: {
    inventory: 'stores-master',
    'purchase-order': 'purchase-orders',
    purchaseorder: 'purchase-orders',
    'item-opening-stock': 'item-opening-stock',
    'internal-item-issue': 'internal-item-issue',
  },
  labelAliases: {
    storemaster: 'stores-master',
    uommaster: 'uom-master',
    suppliermaster: 'supplier-master',
    itemcategory: 'item-category',
    itemsubcategory: 'item-sub-category',
    brandmaster: 'brand-master',
    itemmaster: 'item-master',
    openingstock: 'item-opening-stock',
    purchaseorder: 'purchase-orders',
    stockreceiptvoucher: 'stock-receipt-voucher',
    purchasereturns: 'purchase-returns',
    internalindent: 'internal-indent',
    internalissue: 'internal-item-issue',
    internalreturn: 'internal-item-return',
    'internal-item-return': 'internal-item-return',
    stockledger: 'stock-ledger',
    'stock-ledger': 'stock-ledger',
  },
  routes: [
    r('stores-master', 'Store Master', 'Inventory store locations.', 'master'),
    r('uom-master', 'UOM Master', 'Units of measure.', 'master'),
    r('supplier-master', 'Supplier Master', 'Supplier directory.', 'master'),
    r('item-category', 'Item Category', 'Item category master.', 'master'),
    r('item-sub-category', 'Item Sub Category', 'Item sub-category master.', 'master'),
    r('brand-master', 'Brand Master', 'Brand master.', 'master'),
    r('item-master', 'Item Master', 'Inventory items.', 'master'),
    r('item-opening-stock', 'Opening Stock', 'Opening stock entries.', 'transaction'),
    r('purchase-orders', 'Purchase Order', 'Purchase order list.', 'transaction'),
    r('purchase-order/add', 'Add Purchase Order', 'Create purchase order.', 'transaction'),
    r('purchase-order/edit', 'Edit Purchase Order', 'Edit purchase order.', 'transaction'),
    r('stock-receipt-voucher', 'Stock Receipt Voucher', 'Goods receipt vouchers.', 'transaction'),
    r('stock-receipt-voucher/add', 'Add Stock Receipt Voucher', 'Create SRV.', 'transaction'),
    r('stock-receipt-voucher/edit', 'Edit Stock Receipt Voucher', 'Edit SRV.', 'transaction'),
    r('purchase-returns', 'Purchase Returns', 'Purchase return list.', 'transaction'),
    r('purchase-returns/add', 'Add Purchase Return', 'Create purchase return.', 'transaction'),
    r('purchase-returns/edit', 'Edit Purchase Return', 'Edit purchase return.', 'transaction'),
    r('internal-indent', 'Internal Indent', 'Internal indent list.', 'transaction'),
    r('internal-indent/add', 'Add Internal Indent', 'Create internal indent.', 'transaction'),
    r('internal-indent/edit', 'Edit Internal Indent', 'Edit internal indent.', 'transaction'),
    r('internal-item-issue', 'Internal Issue', 'Internal item issue list.', 'transaction'),
    r('internal-item-issue/add', 'Add Internal Issue', 'Create internal issue.', 'transaction'),
    r('internal-item-return', 'Internal Return', 'Internal item return list.', 'transaction'),
    r('internal-item-return/add', 'Add Internal Return', 'Create internal return.', 'transaction'),
    r('internal-item-return/edit', 'Edit Internal Return', 'Edit internal return.', 'transaction'),
    r('stock-ledger', 'Stock Ledger', 'Inventory stock ledger entries.', 'transaction'),
  ],
}

export const EVENTS_MODULE: ErpModuleMirrorConfig = {
  id: 'events',
  basePath: '/events',
  angularSegment: 'events-and-notifications/',
  defaultSlug: 'events-dashboard',
  moduleLabel: 'Events',
  dashboardTitle: 'Events',
  dashboardDescription:
    'College events, department activities, and calendars — mirrored from Angular events-and-notifications and event-calendar.',
  slugAliases: {
    events: 'events-dashboard',
    'events-calendar': 'events-calendar',
    'staff-events': 'staff-events',
    'school-calendar': 'school-calendar',
    'college-calendar': 'college-calendar',
    'add-event': 'add-event',
    'event-type': 'event-type',
    'department-events': 'department-events',
  },
  labelAliases: {
    eventsdashboard: 'events-dashboard',
    addevent: 'add-event',
    eventtype: 'event-type',
    departmentevents: 'department-events',
    collegecalendar: 'college-calendar',
    eventscalendar: 'events-calendar',
    staffevents: 'staff-events',
    schoolcalendar: 'school-calendar',
  },
  routes: [
    r('events-dashboard', 'Events Dashboard', 'Events module hub.', 'dashboard'),
    r('add-event', 'Add Event', 'Schedule college events (month calendar).', 'transaction'),
    r('event-type', 'Event Type', 'Event type master.', 'master'),
    r('department-events', 'Department Events', 'Department-level events.', 'transaction'),
    r('college-calendar', 'College Calendar', 'College-wide calendar view.', 'transaction'),
    r('events-calendar', 'Events Calendar', 'Student events calendar.', 'transaction'),
    r('staff-events', 'Staff Events', 'Staff events calendar.', 'transaction'),
    r('school-calendar', 'School Calendar', 'School holidays calendar.', 'transaction'),
  ],
}

export const FINANCE_MODULE: ErpModuleMirrorConfig = {
  id: 'finance',
  basePath: '/finance',
  angularSegment: 'finance/',
  defaultSlug: 'finance-dashboard',
  moduleLabel: 'Finance',
  dashboardTitle: 'Finance',
  dashboardDescription:
    'Account entities, chart of accounts, categories, transactions, books, budget, and cheque management.',
  slugAliases: {
    finance: 'finance-dashboard',
    accounts: 'accounts',
    'account-types': 'acoounts-types',
    accounttypes: 'acoounts-types',
    acoountstypes: 'acoounts-types',
    'finance-category': 'finance-category',
    'finance-subcategory': 'finance-subcategory',
    transaction: 'transaction',
    'journal-book': 'journal-book',
    'bank-book': 'bank-book',
    'cash-book': 'cash-book',
    budget: 'budget',
    'finance-reports': 'finance-reports',
    'budget-estimations': 'budget-estimations',
    'budget-proposal': 'budget-proposal',
    'days-book-report': 'days-book-report',
    'budget-approval': 'budget-approval',
    'check-issue': 'check-issue',
    'bank-accounts': 'bank-accounts',
    'check-book': 'check-book',
  },
  labelAliases: {
    financedashboard: 'finance-dashboard',
    accountentity: 'accounts',
    accounttypes: 'acoounts-types',
    financecategory: 'finance-category',
    financesubcategory: 'finance-subcategory',
    incomeandexpenses: 'transaction',
    journalbook: 'journal-book',
    bankbook: 'bank-book',
    cashbook: 'cash-book',
    financereports: 'finance-reports',
    budgetestimations: 'budget-estimations',
    budgetproposal: 'budget-proposal',
    daysbookreport: 'days-book-report',
    budgetapproval: 'budget-approval',
    checkissue: 'check-issue',
    bankaccounts: 'bank-accounts',
    chequebook: 'check-book',
    checkbook: 'check-book',
  },
  routes: [
    r('finance-dashboard', 'Finance Dashboard', 'Finance module hub.', 'dashboard'),
    r('accounts', 'Accounts', 'Finance account entities.', 'master'),
    r('acoounts-types', 'Account Types', 'Chart of account types (Angular typo preserved).', 'master'),
    r('finance-category', 'Finance Category', 'Income/expense categories.', 'master'),
    r('finance-subcategory', 'Finance Sub Category', 'Finance sub-categories.', 'master'),
    r('transaction', 'Income & Expenses', 'Financial transactions.', 'transaction'),
    r('journal-book', 'Journal Book', 'Journal register.', 'report'),
    r('bank-book', 'Bank Book', 'Bank book report.', 'report'),
    r('cash-book', 'Cash Book', 'Cash book report.', 'report'),
    r('budget', 'Budget', 'Budget management.', 'transaction'),
    r('finance-reports', 'Finance Reports', 'Finance reporting.', 'report'),
    r('budget-estimations', 'Budget Estimations', 'Mid-year budget estimations.', 'transaction'),
    r('budget-proposal', 'Budget Proposal', 'Budget proposal workflow.', 'transaction'),
    r('days-book-report', 'Days Book Report', 'Daily book report.', 'report'),
    r('budget-approval', 'Budget Approval', 'Budget approval.', 'transaction'),
    r('check-issue', 'Cheque Issue', 'Issue cheques.', 'transaction'),
    r('bank-accounts', 'Bank Accounts', 'Bank account master.', 'master'),
    r('check-book', 'Cheque Book', 'Cheque book master.', 'master'),
  ],
}

export const WALLET_MODULE: ErpModuleMirrorConfig = {
  id: 'wallet',
  basePath: '/wallet',
  angularSegment: 'wallet/',
  defaultSlug: 'wallet-dashboard',
  moduleLabel: 'Wallet',
  dashboardTitle: 'Wallet',
  dashboardDescription:
    'University payment wallet accounts, transactions, and recharge via payment gateway.',
  slugAliases: {
    wallet: 'wallet-dashboard',
    'university-payment-wallet': 'university-payment-wallet',
    universitypaymentwallet: 'university-payment-wallet',
    'univ-payment-wallet': 'university-payment-wallet',
    univpaymentwallet: 'university-payment-wallet',
    'university-payment-wallet-transactions': 'university-payment-wallet-transactions',
    universitypaymentwallettransactions: 'university-payment-wallet-transactions',
    'wallet-transactions': 'university-payment-wallet-transactions',
    wallettransactions: 'university-payment-wallet-transactions',
    'university-wallet-transactions': 'university-payment-wallet-transactions',
    universitywallettransactions: 'university-payment-wallet-transactions',
    'payment-wallet': 'payment-wallet',
    paymentwallet: 'payment-wallet',
    'recharge-wallet': 'recharge-wallet',
    rechargewallet: 'recharge-wallet',
    'university-wallet-recharge': 'recharge-wallet',
    universitywalletrecharge: 'recharge-wallet',
  },
  labelAliases: {
    walletdashboard: 'wallet-dashboard',
    universitypaymentwallet: 'university-payment-wallet',
    universitypaymentwallettransactions: 'university-payment-wallet-transactions',
    wallettransactions: 'university-payment-wallet-transactions',
    universitywallettransactions: 'university-payment-wallet-transactions',
    paymentwallet: 'payment-wallet',
    rechargewallet: 'recharge-wallet',
    universitywallet: 'university-payment-wallet',
    univpaymentwallet: 'university-payment-wallet',
  },
  routes: [
    r('wallet-dashboard', 'Wallet Dashboard', 'Wallet module hub.', 'dashboard'),
    r('university-payment-wallet', 'University Payment Wallet', 'Wallet balance, pay now, and recent transactions.', 'transaction'),
    r('university-payment-wallet-transactions', 'University Payment Wallet Transactions', 'Full wallet passbook / transaction history.', 'report'),
    r('payment-wallet', 'Payment Wallet Master', 'Admin payment wallet accounts.', 'master'),
    r('recharge-wallet', 'Recharge Wallet', 'Add money via payment gateway.', 'transaction'),
  ],
}

export const ERP_MODULE_REGISTRY: ErpModuleMirrorConfig[] = [
  TRANSPORT_MODULE,
  TC_NO_DUE_MODULE,
  HOSTEL_MODULE,
  CERTIFICATES_MODULE,
  CAMPUS_MAINTENANCE_MODULE,
  TRAININGS_MODULE,
  PLACEMENTS_MODULE,
  COMMITTEES_MODULE,
  INVENTORY_MODULE,
  EVENTS_MODULE,
  FINANCE_MODULE,
  WALLET_MODULE,
]

export const ERP_MODULE_BY_ID = Object.fromEntries(
  ERP_MODULE_REGISTRY.map((m) => [m.id, m]),
) as Record<string, ErpModuleMirrorConfig>
