/**
 * Entity registry — maps every Spring Boot entity class name to its primary key field.
 *
 * Usage:
 *   import { ENTITIES } from '@/config/constants/entities'
 *   domainCreate(ENTITIES.EXAM_SESSION.name, data)
 *   domainUpdate(ENTITIES.EXAM_SESSION.name, ENTITIES.EXAM_SESSION.pk, id, data)
 */
export const ENTITIES = {
  // ─── Examination ─────────────────────────────────────────────────────────────
  EXAM_SESSION:           { name: 'ExamSession',               pk: 'examSessionId'               },
  EXAM_GRADE:             { name: 'ExamGrade',                 pk: 'examGradesId'                }, // pk is examGradesId (with 's') per Spring Boot entity
  EXAM_MAX_MARKS:         { name: 'ExamMaxMarks',              pk: 'examMaxMarksId'              },
  EXAM_MARKS_SETUP:       { name: 'ExamMarkssetup',            pk: 'markssetupId'                }, // note lowercase 's' in entity name; pk is markssetupId (not examMarkssetupId)
  EXAM_FEE_SETUP:         { name: 'ExamFeeSetup',              pk: 'examFeeSetupId'              },
  EXAM_TIMETABLE:         { name: 'ExamTimetable',             pk: 'examTimetableId'             },
  EXAM_MASTER:            { name: 'ExamMaster',                pk: 'examId'                      },
  EXAM_MASTER_DETAILS:    { name: 'ExamMasterDetails',         pk: 'examMasterDetailsId'         },
  EXAM_FEE_STRUCTURE:     { name: 'ExamFeeStructure',          pk: 'examFeeStructureId'          },
  /** FCAR exam setup master (marks setup name, regulations, result validation) — Angular `ExamFCARSetupMaster`. */
  EXAM_FCAR_SETUP_MASTER: { name: 'ExamFCARSetupMaster',     pk: 'examFCARSetMasterId'         },
  EXAM_ROOM_ALLOTMENT:    { name: 'ExamRoomAllotment',         pk: 'examRoomAllotmentId'         },
  SEATING_PLAN:           { name: 'SeatingPlan',               pk: 'seatingPlanId'               },
  INVIGILATOR:            { name: 'InvigilatorRemuneration',   pk: 'invigilatorRemunerationId'   },
  REVALUATION_FEE:        { name: 'RevaluationFee',            pk: 'revaluationFeeId'            },
  // ─── Organisation ────────────────────────────────────────────────────────────
  ORGANIZATION:           { name: 'Organization',              pk: 'organizationId'              },
  CAMPUS:                 { name: 'Campus',                    pk: 'campusId'                    },
  UNIVERSITIES:           { name: 'Universities',              pk: 'universityId'                },
  COLLEGE:                { name: 'College',                   pk: 'collegeId'                   },
  DEPARTMENT:             { name: 'Department',                pk: 'departmentId'                },
  DESIGNATION:            { name: 'Designation',               pk: 'designationId'               },
  BUILDING:               { name: 'Building',                  pk: 'buildingId'                  },
  BLOCK:                  { name: 'Block',                     pk: 'blockId'                     },
  FLOOR:                  { name: 'Floor',                     pk: 'floorId'                     },
  ROOM_TYPE:              { name: 'RoomType',                  pk: 'roomTypeId'                  },
  GENERAL_SETTING:        { name: 'GeneralSetting',            pk: 'generalSettingId'            },
  // ─── Geo hierarchy ───────────────────────────────────────────────────────────
  COUNTRY:                { name: 'Country',                   pk: 'countryId'                   },
  STATE:                  { name: 'State',                     pk: 'stateId'                     },
  DISTRICT:               { name: 'District',                  pk: 'districtId'                  },
  CITY:                   { name: 'City',                      pk: 'cityId'                      },
  // ─── Question Bank ───────────────────────────────────────────────────────────
  ASSESSMENT:              { name: 'Assessment',              pk: 'assessmentId'              },
  COURSE_QUESTION:         { name: 'CourseQuestion',          pk: 'courseQuestionId'          },
  // ─── Reference / lookup ──────────────────────────────────────────────────────
  GENERAL_DETAIL:         { name: 'GeneralDetail',             pk: 'generalDetailId'             },
  REGULATION:             { name: 'Regulation',                pk: 'regulationId'                },
  COURSE_GROUP:           { name: 'CourseGroup',               pk: 'courseGroupId'               },
  COURSE_YEAR:            { name: 'CourseYear',                pk: 'courseYearId'                },
  COURSE_TYPE:            { name: 'CourseType',                pk: 'courseTypeId'                },
  COURSE:                 { name: 'Course',                    pk: 'courseId'                    },
  GROUP_SECTION:          { name: 'GroupSection',              pk: 'groupSectionId'              },
  BATCH:                  { name: 'Batch',                     pk: 'batchId'                     },
  STUDENT_ACADEMIC_BATCH: { name: 'StudentAcademicbatch',      pk: 'studentAcademicbatchId'      },
  ACADEMIC_YEAR:          { name: 'AcademicYear',              pk: 'academicYearId'              },
  FINANCIAL_YEAR:         { name: 'FinancialYear',             pk: 'financialYearId'             },
  SUBJECT:                { name: 'Subject',                   pk: 'subjectId'                   },
  ROOM:                   { name: 'Room',                      pk: 'roomId'                      },
  BANK:                   { name: 'Bank',                      pk: 'bankId'                      },
  GENERAL_MASTER:         { name: 'GeneralMaster',             pk: 'generalMasterId'             },
  CASTE:                  { name: 'Caste',                     pk: 'casteId'                     },
  SUB_CASTE:              { name: 'SubCaste',                  pk: 'subCasteId'                  },
  QUALIFICATION:          { name: 'Qualification',             pk: 'qualificationId'             },
  QUALIFICATION_GROUP:    { name: 'QualificationGroup',        pk: 'qualificationGroupId'        },
  COLLEGE_CALENDAR:       { name: 'CollegeCalendar',           pk: 'collegeCalendarId'           },
  WORKFLOW_STAGE:         { name: 'WorkflowStage',             pk: 'workflowStageId'             },
  STUDENT_CATEGORY:       { name: 'StudentCategory',           pk: 'studentCatId'                },
  WORKFLOW_MEMBER_AUTHORIZATION: { name: 'WorkflowMemberAuthorization', pk: 'wfMemberAuthorizationId' },
  COLLEGE_CERTIFICATE:    { name: 'CollegeCertificate',        pk: 'collegeCertificateId'        },
  DOCUMENT_REPOSITORY:    { name: 'DocumentRepository',        pk: 'documentRepositoryId'        },
  WEEKDAY:                { name: 'Weekday',                   pk: 'weekdayId'                   },
  // ─── Accounts & Fees — Fee Masters ───────────────────────────────────────────
  FEE_CATEGORY:           { name: 'FeeCategory',               pk: 'feeCategoryId'               },
  FEE_PARTICULAR:         { name: 'FeeParticular',             pk: 'feeParticularsId'            },
  UNIV_FEE_STRUCTURE:     { name: 'UnivFeeStructure',          pk: 'univFeeStructureId'          },
  UNIV_FEE_STRUCTURE_DETAILS: { name: 'UnivFeeStructureDetails', pk: 'univFeeStructureDetId'   },
  // ─── Scholarship Management ──────────────────────────────────────────────────
  SCHOLARSHIP_TYPE:       { name: 'ScholarshipType',           pk: 'scholarshipTypeId'           },
  SCHOLARSHIP_VALUE:      { name: 'ScholarshipValue',          pk: 'scholarshipValueId'          },
  SCH_STD_APPLICATION:    { name: 'SchStdApplication',         pk: 'schStdApplicationId'         },
  SCH_PRECEEDING:         { name: 'SchPreceeding',             pk: 'schPreceedingId'             },
  SCH_STD_PRECEEDING:     { name: 'SchStdPreceeding',          pk: 'schStdPreceedingId'          },
  SCH_ACCOUNTS_PRECEEDING:{ name: 'SchAccountsPreceeding',     pk: 'schAccountsPreceedingId'     },
  FEE_SCH_STRUCTURE:      { name: 'FeeSchStructure',           pk: 'feeSchStructureId'           },
  // ─── Admission ───────────────────────────────────────────────────────────────
  STUDENT_APPLICATION_FORM: { name: 'studentapplicationform',  pk: 'studentAppId'                },
  STUDENT_APPLICATION_FORMS:{ name: 'studentapplicationforms', pk: 'studentAppId'                },
  STUDENT_ENQUIRY:          { name: 'StudentEnquiry',            pk: 'enquiryId'                   },
  CASTE_QUOTA:              { name: 'CasteQuota',                pk: 'casteQuotaId'                },
  UNIV_COLLEGE_COUNSELLING: { name: 'UnivCollegeCounselling',    pk: 'univCollegeCounsellingId'    },
  UNIV_STD_APPLICATIONS:    { name: 'UnivStdApplications',         pk: 'univAppId'                   },
  UNIV_ADMISSION_ALLOTMENT: { name: 'UnivAdmissionAllotment',      pk: 'univAdmissionAllotmentId'    },
  UNIV_ADMISSION_ALLOTMENT_DETAILS: { name: 'UnivAdmissionAllotmentDetails', pk: 'univAdmissionAllotmentDetId' },
  // ─── E-Office ────────────────────────────────────────────────────────────────
  OFFICE_LETTER_FORMATS:    { name: 'OfficeLetterFormats',    pk: 'officeLetterFormatsId' },
  INV_INTERNAL_INDENT:      { name: 'InvInternalIndent',      pk: 'internalIndId'         },
  INV_PURCHASE_ORDER:       { name: 'InvPurchaseOrder',       pk: 'poId'                  },
  INV_STORES_MASTER:        { name: 'InvStoresmaster',        pk: 'storeId'               },
  INV_SUPPLIER_MASTER:      { name: 'InvSuppliermaster',      pk: 'supplierId'            },
  INV_ITEM_MASTER:          { name: 'InvItemmaster',          pk: 'itemId'                },
  // ─── Affiliated Colleges ─────────────────────────────────────────────────────
  UNIV_COLLEGE_WISE_PAYMENT: { name: 'UnivCollegeWisePayments', pk: 'univCollegeWisePaymentId' },
  // ─── HR & Payroll ────────────────────────────────────────────────────────────
  PAYROLL_CATEGORY:        { name: 'PayrollCategory',        pk: 'payrollCategoryId'        },
  EMP_DEPT_HEADS:          { name: 'EmpDeptHeads',           pk: 'empDeptHeadId'            },
  PAYSLIP_SETTING:         { name: 'PayslipSetting',         pk: 'payslipSettingId'         },
  LEAVE_TYPE:              { name: 'LeaveType',              pk: 'leaveTypeId'              },
  LEAVE_ENTITLEMENT:       { name: 'LeaveEntitlement',       pk: 'leaveEntitlementId'     },
  LEAVE_APPLICATION:       { name: 'LeaveApplication',       pk: 'leaveApplicationId'     },
  EMPLOYEE_DETAIL:         { name: 'EmployeeDetail',         pk: 'employeeId'             },
  EMPLOYEE_REPORTING:      { name: 'EmployeeReporting',      pk: 'employeeReportingId'    },
  EMP_PERF_ASSESSMENT_FEEDBACK: { name: 'EmpPerfAssessmentFeedback', pk: 'assessmentFeedbackId' },
  EMP_SELF_APPRAISAL_FORM:     { name: 'EmpSelfappraisalForm',     pk: 'selfAppraisalFormId'     },
  EMP_ATTENDANCE_EMPLOYEE:     { name: 'EmpAttendanceEmployee',    pk: 'attendanceEmpsId'        },
  SHIFT:                       { name: 'Shift',                    pk: 'shiftId'                 },
  EMPLOYEE_SHIFT:              { name: 'EmployeeShift',            pk: 'empShiftId'              },
  // ─── Mentorship / counseling ───────────────────────────────────────────────
  COUNSELOR_ACTIVITY_TYPE:     { name: 'CounselorActivityType',  pk: 'counselorActivityTypeId' },
  COUNSELOR_ACTIVITY:            { name: 'CounselorActivity',      pk: 'counselorActivityId'       },
  COUNSELOR_MAPPING:             { name: 'CounselorMapping',     pk: 'counselorId'               },
  // ─── Events ────────────────────────────────────────────────────────────────
  EVENT_TYPE:                    { name: 'EventType',            pk: 'eventTypeId'               },
  EVENT:                         { name: 'Event',                pk: 'eventId'                   },
  DEPARTMENT_EVENT:              { name: 'DepartmentEvent',      pk: 'deptEventId'               },
  // ─── Library ───────────────────────────────────────────────────────────────
  LIBRARY_DETAIL:                { name: 'LibraryDetail',          pk: 'libraryId'                 },
  LIB_AUTHOR:                    { name: 'Author',                 pk: 'authorId'                  },
  LIB_PUBLISHER:                 { name: 'Publisher',              pk: 'publisherId'               },
  LIB_BOOK_CATEGORY:             { name: 'Bookcategory',           pk: 'bookcatId'                 },
  LIB_LIBRARY_CATEGORY:          { name: 'LibraryCategory',        pk: 'libCategoryId'             },
  LIB_SUPPLIER:                  { name: 'LibSupplierDetail',      pk: 'supplierId'                },
  LIB_RACK:                      { name: 'LibShelve',              pk: 'shelveId'                  },
  LIB_MEMBERSHIP:                { name: 'MemberShip',             pk: 'memberShipId'              },
  LIB_BOOK:                      { name: 'Book',                   pk: 'bookId'                    },
  LIB_PERIODICAL:                { name: 'Periodical',             pk: 'periodicalId'              },
  LIB_BOOK_DETAIL:               { name: 'BookDetail',             pk: 'bookDetailsId'             },
  LIB_BOOK_PURCHASE:             { name: 'BookPurchaseDetail',     pk: 'bookPurchaseDetailId'      },
  LIB_SETTING:                   { name: 'LibrarySetting',         pk: 'libSettingsId'             },
  // ─── Transport ─────────────────────────────────────────────────────────────
  TRANSPORT_DETAIL:              { name: 'TransportDetail',        pk: 'transportDetailId'         },
  VEHICLE_DETAIL:                { name: 'VehicleDetail',          pk: 'vehicleDetailId'           },
  DRIVER:                        { name: 'Driver',                 pk: 'driverId'                  },
  HELPER:                        { name: 'Helper',                 pk: 'helperId'                  },
  ROUTE:                         { name: 'Route',                  pk: 'routeId'                   },
  ROUTE_STOP:                    { name: 'RouteStop',              pk: 'routeStopId'               },
  VEHICLE_DRIVER:                { name: 'VehicleDriver',          pk: 'vehicleDriverId'           },
  VEHICLE_ROUTE:                 { name: 'VechicleRoute',          pk: 'vechicleRouteId'           },
  DISTANCE_FEE:                  { name: 'DistanceFee',            pk: 'distanceFeeId'             },
  TRANSPORT_ALLOCATION:          { name: 'TransportAllocation',    pk: 'transportAllocationId'     },
  // ─── TC & No Due / Certificates ────────────────────────────────────────────
  FEE_CERTIFICATE_ISSUE:         { name: 'FeeCertificateIssue',    pk: 'feeCertificateIssueId'     },
  FEE_CERTIFICATE_WORKFLOW:      { name: 'FeeCertificateWorkflow', pk: 'feeCertificateWorkflowId'  },
  // ─── Hostel ────────────────────────────────────────────────────────────────
  HOSTEL_TYPE:                   { name: 'HostelType',               pk: 'hostelTypeId'                },
  HOSTEL_DETAIL:                 { name: 'HostelDetail',             pk: 'hostelId'                    },
  HOSTEL_ROOM_CHARGE:            { name: 'HostelRoomCharge',         pk: 'hstlRoomChargesId'           },
  HOSTEL_ROOM:                   { name: 'HostelRoom',               pk: 'hstlRoomId'                  },
  HOSTEL_ROOM_ALLOCATION:        { name: 'HostelRoomAllocation',   pk: 'hstlRoomAllotId'             },
  HOSTEL_DISCOUNT:               { name: 'HostelDiscount',           pk: 'hstlDiscountId'              },
  HOSTEL_REGISTER:               { name: 'HostelRegister',           pk: 'hstlRegisterId'              },
  HOSTEL_VISITOR:                { name: 'HostelVisitor',            pk: 'hstlVisitorId'               },
} as const

export type EntityKey = keyof typeof ENTITIES
